import Head from 'next/head'
import Image from 'next/image'
import SideBar from '../components/SideBar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>WhatsApp Clone</title>
        <meta name="description" content="Generated by inhdanh" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SideBar />
    </div>
  )
}
